Improved shadowban
TyNoOutlet/BanIt pull request #4
Opened 2021-03-02 22:01 UTC by ccuser44

Unready I will complete tomorrow

2021-03-02 22:37 UTC, TyNoOutlet reviewed
This looks really good! I'll approve this when you've finished most likely.

2021-03-03 14:21 UTC, ccuser44 commented
Ok so I made a change to the pull where it is more likely to put _"Client Not Responding [Client hasn't checked in >5 minutes]"_ as the kick reason than the other reasons. I am not sure if this is a good thing. That kick message is a legit kick message made by an admin command system. However I am not sure if displaying it more often is a good idea or not. What's your opinion on this?

2021-03-03 14:27 UTC, ccuser44 commented
Also should the network ownership thing always happen to shadowbanned people? Because it would have an added benefit of always preventing all movement exploiters. Like I mean if you shadowban someone they can still play the game and cause damage by exploiting so it could prevent that.

2021-03-03 18:33 UTC, TyNoOutlet commented
Applying it more often than not is fine. It's pretty convincing. Also, the network ownership thing should always happen. If you haven't already added it so it always happens, could you do that? I'll merge afterwards.

2021-03-03 18:35 UTC, TyNoOutlet requested changes
Already commented what needs changed, will approve afterwards.

2021-03-03 19:46 UTC, ccuser44 commented
Ok done

2021-03-03 20:04 UTC, TyNoOutlet approved these changes

2021-03-03 20:05 UTC, merged